//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRGMOVy
    {
        public string CATEGORYNAME { get; set; }
        public int MOVIEID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CATID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string POSTERIMAGE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> SUPPID { get; set; }
    }
}
