//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRGOrderSupp
    {
        public Nullable<int> MOVIEID { get; set; }
        public int CARTID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ORDERSTATUS { get; set; }
        public Nullable<int> SUPPID { get; set; }
    }
}
