//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCART
    {
        public int CARTID { get; set; }
        public Nullable<int> CUSTID { get; set; }
        public Nullable<int> MOVIEID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> SUPPLIED { get; set; }
    
        public virtual TBCUSTOMER TBCUSTOMER { get; set; }
        public virtual TBCUSTOMER TBCUSTOMER1 { get; set; }
        public virtual TBMOVy TBMOVy { get; set; }
        public virtual TBORDER TBORDER { get; set; }
    }
}
