//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMOVy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBMOVy()
        {
            this.TBCARTs = new HashSet<TBCART>();
        }
    
        public int MOVIEID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CATID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string POSTERIMAGE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> SUPPID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCART> TBCARTs { get; set; }
        public virtual TBCATEGORy TBCATEGORy { get; set; }
        public virtual TBSUPPLIER TBSUPPLIER { get; set; }
    }
}
